### PR TITLE
#35 Set TCP connection name

### PR DESCRIPTION
**Pull request by 0UserName**
Added connection_name property for consumer/producer/locator.

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
Thank you @0UserName 
I will have a look as soon as possible.

**Review by Gsantomaggio — COMMENTED** [review]
The PR looks good. 
Can you please rebase?

I was wondering if there is an easy way to create a test/unit test for it.

**Comment by Gsantomaggio** [comment]
Thank you @0UserName

**Comment by 0UserName** [comment]
Hi!

> Can you please rebase?

Done.

**Comment by 0UserName** [comment]
> I was wondering if there is an easy way to create a test/unit test for it.

Test that the parameter is accepted by the server? I don't quite understand how this can be verified.

**Pull request merged**
