### PR TITLE
Handle CreditResponse when subscription is unknown on server

### PR DESCRIPTION
**Pull request by jonnepmyra**
When calling Close() on a consumer while still handling messages in the consumer messagehandler, the Close() will throw exception, see issue #154 and the Close finally timeouts like:

```
System.TimeoutException: The operation has timed out.
   at RabbitMQ.Stream.Client.ManualResetValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource<T>.GetResult(Int16 token)
   at RabbitMQ.Stream.Client.Client.Request[TIn,TOut](Func`2 request, Nullable`1 timeout)
   at RabbitMQ.Stream.Client.Client.Request[TIn,TOut](Func`2 request, Nullable`1 timeout)
   at RabbitMQ.Stream.Client.Client.Close(String reason)
   at RabbitMQ.Stream.Client.Client.MaybeClose(String reason)
   at RabbitMQ.Stream.Client.Consumer.Close()
```

This PR aims to handle the [CreditResponse that can be issued by the server when the subscription is unknown ](https://github.com/rabbitmq/rabbitmq-server/blob/v3.10.x/deps/rabbitmq_stream/docs/PROTOCOL.adoc#credit) to the server.

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@jonnepmyra thank you for your contribution. 
I changed the message log. It is enough to log the message without checking if the Consumer exists or not.

**Review by Gsantomaggio — APPROVED** [review]

**Comment by Gsantomaggio** [comment]
cc @ricsiLT

**Comment by ricsiLT** [comment]
Neat! Want a test drive before merging? I can certainly arrange that 😏

Also, is this version-specific from RMQ side? Or can I test on whatever 3.10.x?

**Comment by Gsantomaggio** [comment]
>Or can I test on whatever 3.10.x?

yes you can use `3.10.x` Thank you

**Comment by ricsiLT** [comment]
Works like charm!

**Comment by Gsantomaggio** [comment]
Thank you all

**Pull request merged**
