### PR TITLE
Add debug info during the login step

### PR DESCRIPTION
**Pull request by Gsantomaggio**
- Add more debug info to better understand the startup step.
- print the server properties 

Releated to https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/299

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@aeb-dev 
Do you have a chance to test the PR?  
it adds more debug information to understand what's going on.

Please enable the logs in debug mode.
Thank you

**Comment by aeb-dev** [comment]
Sorry, I could not allocate time yet to test it. I will let you know as soon as possible

**Comment by Gsantomaggio** [comment]
@aeb-dev Ok no problem. I tried to reproduce the issue with the [configuration you provided ](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/299#issuecomment-1720169350) and it works.


Screenshot 2023-09-18 at 15 25 11

conf:
```csharp
  var config = new StreamSystemConfig()
        {
            
            UserName = "test",
            Password = "test",
            VirtualHost = "test",
            AddressResolver = new AddressResolver(new DnsEndPoint("localhost", 30552)),
            Endpoints = new List<EndPoint> { new DnsEndPoint("localhost", 30552) },
        
        };
        var system = await StreamSystem.Create(config, streamLogger).ConfigureAwait(false);
```

Logs:
```
dbug: RabbitMQ.Stream.Client.StreamSystem[0]
      Server properties: [cluster_name, main-rabbitmq], [copyright, Copyright (c) 2007-2023 VMware, Inc. or its affiliates.], [information, Licensed under the MPL 2.0. Website: https://rabbitmq.com], [platform, Erlang/OTP 26.0.2], [product, RabbitMQ], [version, 3.13.0-beta.6]
dbug: RabbitMQ.Stream.Client.StreamSystem[0]
      Sasl mechanism: AMQPLAIN, PLAIN
dbug: RabbitMQ.Stream.Client.StreamSystem[0]
      Open: ConnectionProperties: [advertised_port, 5552], [advertised_host, main-rabbitmq-server-0.main-rabbitmq-nodes.default]
dbug: RabbitMQ.Stream.Client.StreamSystem[0]
      Extracted BrokerVersion version: 3.13.0
dbug: RabbitMQ.Stream.Client.StreamSystem[0]
      Client connected to Unspecified/localhost:30552
info: Filter.FilterConsumer[0]
```

I'll be looking forward to your feedback since I can't reproduce it.

**Comment by aeb-dev** [comment]
I get this log: Extracted BrokerVersion version: 3.13.0

**Comment by aeb-dev** [comment]
Okay, I found the problem.

Before testing for consumer filters I had another rabbitmq installed so I had updated that to test it. So after update, the new rabbitmq was using the old data of old rabbitmq.

You can produce the error with the following approach but I think this might not be a client problem:

First deploy rabbitmq with:
```yaml
image: docker.io/rabbitmq:3.11.5
```

then update
```yaml
image: docker.io/rabbitmq:3.13-rc-management
```

Then re-run the code from the issue.

Note: If I do a clean install everything works fine

**Comment by Gsantomaggio** [comment]
You have to enable the feature flags. Coming from an old version, the filter is disabled. 
Screenshot 2023-09-18 at 17 17 48

**Comment by aeb-dev** [comment]
After enabling, everything works as expected thanks

**Comment by Gsantomaggio** [comment]
I added the [feature flag](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/301/files#diff-b08ff9a3d581af9df4f7e209452830c93f2367debb487e937e158870332fbd1eL85-L87) info in case of problem. That would help in the same situation

**Review by Zerpet — APPROVED** [review]

**Pull request merged**
