### PR TITLE
Add Connection Pool Close configuration

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Closes: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/388

### CODE REVIEW

**Comment by Gsantomaggio** [comment]
@jonnepmyra Can you please test it?
```csharp
                ConnectionPoolConfig = new ConnectionPoolConfig()
                {
                    ConnectionCloseConfig = new ConnectionCloseConfig()
                    {
                        Policy = ConnectionClosePolicy.CloseWhenEmptyAndIdle,
                        IdleTime = TimeSpan.FromSeconds(60)
                    }
                }
```

**Comment by jonnepmyra** [comment]
Wow, that was fast :) , thank you!

I'm afraid that I will not be as fast ;),  it may take a little longer than usual to test due to the holiday period, but I'll test as soon as possible!

**Comment by Gsantomaggio** [comment]
Thanks a lot @lukebakken 

Here https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/1814584722be71c15adfe41cefdeb4827725287a/RabbitMQ.Stream.Client/ConnectionsPool.cs#L212

You raised a good point and an old "problem" of this client:
When you close the `StreamSystem,` the producers and consumers created by `StreamSystem` won't be closed. 

The behaviour is different from Java and Go, see for [example, Go Stream Client](https://github.com/rabbitmq/rabbitmq-stream-go-client/blob/baed3d514424e0924142231059167ad1c1598f5b/pkg/stream/environment.go#L264-L269 
) 
 

We should also add this behaviour to this client, but it will introduce a sort of breaking change. Can we think of a 1.9 version? 

The change has to deal with the auto-reconnect feature and close all the producers and consumers in the right way to avoid triggering the auto-reconnection

**Comment by Gsantomaggio** [comment]
@lukebakken To avoid inconsistency, I added a check during the [pool connection close](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/389/files#diff-c0155414eac5347211d45756c09892d1488460eb4ba5ca6944260d95243867b9R431)  only in case the policy  is `CloseWhenEmptyAndIdle` 

That is not perfect, but it could be enough for the moment.

Version 2.0, we can think of adopting the same Golang and Java behaviour: 
```
Close all the Producers and Consumers when the System is closed. 
```
This is a breaking change that I want to avoid introducing in this version. 


With the policy `CloseWhenEmpty` ( default ) won't change anything btw. 

@jonnepmyra thoughts?

**Pull request merged**
