### PR TITLE
Fix "Data instances with a length of 255 bytes are wrongly written"

### PR DESCRIPTION
**Pull request by lukebakken**
See #160

### CODE REVIEW

**Comment by lukebakken** [comment]
@Timz95 - when I repeatedly run the new tests on Linux, I sometimes get this failure:

```
  Passed Tests.UnitTests.CompressUnCompressShouldHaveTheSize [908 ms]
[xUnit.net 00:01:35.48]     Tests.IntegrationTest.TestEventLength(event: System.Buffers.ReadOnlySequence<Byte>[254]) [FAIL]
[xUnit.net 00:01:35.49]       System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
[xUnit.net 00:01:35.49]       Stack Trace:
[xUnit.net 00:01:35.49]            at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[xUnit.net 00:01:35.49]            at System.Collections.Generic.List`1.Enumerator.MoveNext()
[xUnit.net 00:01:35.49]            at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
[xUnit.net 00:01:35.49]         /home/lbakken/development/rabbitmq/rabbitmq-stream-dotnet-client/Tests/IntegrationTest.cs(72,0): at Tests.IntegrationTest.<>c__DisplayClass2_0.<TestEventLength>b__3()
[xUnit.net 00:01:35.49]         /home/lbakken/development/rabbitmq/rabbitmq-stream-dotnet-client/Tests/IntegrationTest.cs(95,0): at Tests.IntegrationTest.WaitForConditionAsync(Func`1 condition, Int32 timeoutMs, Int32 pollingInterval)
[xUnit.net 00:01:35.49]         /home/lbakken/development/rabbitmq/rabbitmq-stream-dotnet-client/Tests/IntegrationTest.cs(71,0): at Tests.IntegrationTest.TestEventLength(ReadOnlySequence`1 event)
[xUnit.net 00:01:35.49]         --- End of stack trace from previous location ---
[xUnit.net 00:01:35.49]       Output:
[xUnit.net 00:01:35.49]         Event received with size: 259 - Content Length: 254
[xUnit.net 00:01:35.49]         Event published with PublishingId: 0 - Ok
[xUnit.net 00:01:35.67]   Finished:    Tests
  Passed Tests.UnitTests.AddressResolverLoadBalancerSimulate [1 s]
  Passed Tests.StreamSpecTests.DefaultStreamSpecMustHaveAtLeastQueueLeaderLocator [1 ms]
  Passed Tests.StreamSpecTests.CanOverrideAnyStreamSpecAttributes [2 ms]
  Failed Tests.IntegrationTest.TestEventLength(event: System.Buffers.ReadOnlySequence<Byte>[254]) [29 ms]
  Error Message:
   System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
  Stack Trace:
     at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Tests.IntegrationTest.<>c__DisplayClass2_0.<TestEventLength>b__3() in /home/lbakken/development/rabbitmq/rabbitmq-stream-dotnet-client/Tests/IntegrationTest.cs:line 72
   at Tests.IntegrationTest.WaitForConditionAsync(Func`1 condition, Int32 timeoutMs, Int32 pollingInterval) in /home/lbakken/development/rabbitmq/rabbitmq-stream-dotnet-client/Tests/IntegrationTest.cs:line 95
   at Tests.IntegrationTest.TestEventLength(ReadOnlySequence`1 event) in /home/lbakken/development/rabbitmq/rabbitmq-stream-dotnet-client/Tests/IntegrationTest.cs:line 71
--- End of stack trace from previous location ---
  Standard Output Messages:
 Event received with size: 259 - Content Length: 254
 Event published with PublishingId: 0 - Ok


  Passed Tests.IntegrationTest.TestEventLength(event: System.Buffers.ReadOnlySequence<Byte>[255]) [82 ms]
  Standard Output Messages:
 Event published with PublishingId: 0 - Ok
 Event received with size: 260 - Content Length: 255
```

**Comment by Timz95** [comment]
Unfortunately I can't reproduce this on Windows somehow. However, I think the following might be the problem:
The adding of the response codes of sent messages (in the ConfirmHandler) and adding of received messages (in the MessageHandler) to their respective lists, executes in a different thread. Simultaneously, the IEnumerable.Any method is called from the WaitForConditionAsync method. So probably the items are added to their lists, while IEnumerable.Any is enumerating the same list at more or less exactly the same time - which result in that exception.

image

**Comment by Timz95** [comment]
I can't however push to this branch. So you can see a possible solution here: 

https://github.com/Timz95/rabbitmq-stream-dotnet-client/commit/a1dc0fcd6e197f1bf71458e88fefa2c517eea647

**Comment by lukebakken** [comment]
Thanks @Timz95. Yeah, one nice benefit of a PR from your fork is that I could push changes there myself if I needed to. I'll merge that commit into my branch.

**Comment by lukebakken** [comment]
@Timz95 thanks for your contribution! Have a great weekend.

**Review by Zerpet — DISMISSED** [review]
Looks good to me!

**Comment by Gsantomaggio** [comment]
@Timz95 Thank you for your contrition 
I just moved your test to the specific file and make it complain with other the other tests.
@lukebakken @Zerpet, if it is ok with you, I will merge and release a new version. 
This is an important fix.

**Review by Gsantomaggio — APPROVED** [review]

**Comment by Zerpet** [comment]
> @Timz95 Thank you for your contrition I just moved your test to the specific file and make it complain with other the other tests. @lukebakken @Zerpet, if it is ok with you, I will merge and release a new version. This is an important fix.

:shipit: 🚀

**Pull request merged**
