### PR TITLE
#74 Console.WriteLine has been replaced with EventSource

### LINKED ISSUE #74: Use EventSource for logging
See discussion here:

https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/16

### PR DESCRIPTION
**Pull request by 0UserName**
EventSource-based logger that implements the following interface:

```
    internal interface ILogEventSource
    {
        /// <summary>
        /// Writes an informational log message.
        /// </summary>
        /// 
        /// <param name="message">
        /// </param>
        ILogEventSource LogInformation(string message);

        /// <summary>
        /// Writes a warning log message.
        /// </summary>
        /// 
        /// <param name="message">
        /// </param>
        ILogEventSource LogWarning(string message);

        /// <summary>
        /// Writes an error log message.
        /// </summary>
        /// 
        /// <param name="message">
        /// </param>
        ILogEventSource LogError(string message);

        /// <summary>
        /// Writes an error log message.
        /// </summary>
        /// 
        /// <param name="message">
        /// </param>
        /// 
        /// <param name="exception">
        /// The exception to log.
        /// </param>
        ILogEventSource LogError(string message, Exception exception);
    }
```

Also added several tests verifying the basic aspects: event level match, payload name match, payload match (occurrence).

Fixes #74

### CODE REVIEW

**Comment by lukebakken** [comment]
This is great! Thank you. I'll update the ApiApproval test.

**Review by lukebakken — CHANGES_REQUESTED** [review]
Here's one instance of `Console` that needs to be updated:

https://github.com/0UserName/rabbitmq-stream-dotnet-client/blob/%2374/RabbitMQ.Stream.Client/Client.cs#L465

**Comment by lukebakken** [comment]
Would it be possible to make this implementation the same or very similar to here:

https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/main/projects/RabbitMQ.Client/client/logging

If this implementation has advantages, please let me know what they are. Thanks again.

**Comment by 0UserName** [comment]
> Here's one instance of Console that needs to be updated:

Fixed. My bad.


> Would it be possible to make this implementation the same or very similar to here:

I thought the implementations were similar :)


- Initialized properties `Message` and `Keywords` in `Event` attribute:

`[Event(1, Message = "INFO", Keywords = Keywords.Log, Level = EventLevel.Informational)]`

`[Event(2, Message = "WARN", Keywords = Keywords.Log, Level = EventLevel.Warning)]`

`[Event(3, Message = "ERROR", Keywords = Keywords.Log, Level = EventLevel.Error)]`


- Added new methods with a similar signature from the implementation mentioned above::

`public ILogEventSource LogInformation(string message, params object[] args)`

`public ILogEventSource LogWarning(string message, params object[] args)`

`public ILogEventSource LogError(string message, Exception exception, params object[] args)`


- Line break manipulation removed from `LogEventSource`.


---


- There are no [.NET452](https://github.com/rabbitmq/rabbitmq-dotnet-client/blob/main/projects/RabbitMQ.Client/client/logging/RabbitMqClientEventSource.cs#L85) preprocessor directives. Should it be added or can it be ignored? 

 - There is no overload for `RabbitMqExceptionDetail` because there is no exception implementation. Instead, a signature with an argument of type `Exception` is used. Calling `ToString` on an exception will return the [full set](https://referencesource.microsoft.com/#mscorlib/system/exception.cs,438) (message from inner exceptions, etc) of information.
 
 - There is no `ESLog` wrapper class. Instead, the `ILogEventSource` interface is used, which seems to me more logical if the original purpose of the wrapper was to hide details (properties, methods) from the `EventSource`.

**Comment by lukebakken** [comment]
@0UserName thanks for the explanation. It is very valuable to know for a review. This looks great.

**Review by lukebakken — APPROVED** [review]

**Pull request merged**
