### PR TITLE
Add cancellation token during subscribe

### PR DESCRIPTION
**Pull request by Gsantomaggio**
Fixes https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/205

In this way, the thread is not locked, and the:
```csharp
new MessageContext(message.MessageOffset, TimeSpan.FromMilliseconds(chunk.Timestamp)),
                            message).Wait(_token);
```

is in wait(...), so there is not the thread pool exhaustion.

@ricardSiliuk @ricsiLT it should not change anything. Please feel free to add any comments.

@jonnepmyra  do you have a chance to test it? 
 
Signed-off-by: Gabriele Santomaggio <G.santomaggio@gmail.com>

### CODE REVIEW

**Comment by jonnepmyra** [comment]
Hi!

Thank your for the quick response and patch @Gsantomaggio 

We've been testing it during the day with various workloads and it's definitely alot better!

At first we could still se about 0.5% of all closed connections get deadlocked with an error:
`Error removing the consumer id: 0 from the server
`

... but after tweaking our consumer messagehandlers that contained TaskCompletionSources with `TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);` it works better and we're no longer able to reporduce the problem!!

The reason why I'm mentioning the TaskCompletionSource tweak in our application code is that even if it works well now, and we're super grateful for this being fixed, the code still seems to be able to deadlock under certain conditions but I might be wrong... 

The Wait() in:
https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/9d341701b5d3e55e0d9a1d791e3aa0bc88196c8c/RabbitMQ.Stream.Client/RawConsumer.cs#L160-L162



feels so wrong (as mentioned before in https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/106#issuecomment-1240246453 ) but on the other hand, I've no better suggestion at the very moment if `WaitAsync()` leads to thread stravation.

Thanks again!

**Comment by Gsantomaggio** [comment]
@jonnepmyra let me clarify some points:

- We can't use `WaitAsync` since we will end up on https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/184#issuecomment-1326154401


- We can't use aync Tasks here: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/blob/9d341701b5d3e55e0d9a1d791e3aa0bc88196c8c/RabbitMQ.Stream.Client/RawConsumer.cs#L160-L162
Because with `ref SequenceReader`, it is not possible:

```
Parameters of type `SequenceReader<byte>` cannot be declared in async local functions
```

- We introduced `SequenceReader<byte>` for performance problems here: https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/180

- `.Wait(_token); ` should not go in dead-lock (unless there is some blocking code in your consumer).


Have questions:

- > code still seems to be able to deadlock
     - Have you tried without your consumer code to reproduce the lock?
     - What do you mean by deadlock? Do you still have a memory leak? 
     - Have you tried the last commit https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/pull/206/commits/9d341701b5d3e55e0d9a1d791e3aa0bc88196c8c ?
     
Thank you for trying the PR.  :)

p.s. If you want, you can find me at https://rabbitmq-slack.herokuapp.com/

**Comment by jonnepmyra** [comment]
Hi!

Thanks for taking time to explain.

>   * Have you tried without your consumer code to reproduce the lock?

Yes, and I have not been able to reproduce it.

>   * What do you mean by deadlock? Do you still have a memory leak?

The Memoryleak seems to be fixed now, no connections left unclosed after tweaking application specific consumer code!

>   * Have you tried the last commit [9d34170](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/commit/9d341701b5d3e55e0d9a1d791e3aa0bc88196c8c) ?

Yes, it seems fine

Cheers!

**Comment by Gsantomaggio** [comment]
Great! We will merge it soon!
Ty

**Comment by Gsantomaggio** [comment]
Let's wait for some feedback from @ricardSiliuk @ricsiLT then, we can merge and release.

**Pull request merged**
