### PR TITLE
Fix connections to server on different locales

### PR DESCRIPTION
**Pull request by Noonlord**
ToUpper is not enough, we need to use InvariantCulture to be sure that the string is converted to uppercase in a way that is consistent with the server.

### CODE REVIEW

**Comment by Noonlord** [comment]
@Zerpet I would like to have a review if possible.

**Comment by Gsantomaggio** [comment]
Thank you @Noonlord. 
May I ask for an example where the current implementation fails?

**Review by Zerpet — COMMENTED** [review]
I echo Gabriele's thought. Where does the current implementation fail?

From what I read in [Microsoft documentation](https://learn.microsoft.com/en-us/dotnet/api/system.string.toupperinvariant?view=net-7.0), the upper invariant seems important for consistent sorting. However, we are not sorting the authentication mechanism array, we just iterate it.

**Comment by Noonlord** [comment]
@Gsantomaggio although I can not provide you a configuration file at the moment, I can show something else to reproduce the bug locally.

This is the current culture:
resim (2)

This is the auth mechanisms response from server:
resim (1)

And this is the client parameters: 
resim

Issue is from client parameters authentication method enumeration, Plain, converts to string as "Plain" and using TR-tr culture ToUpper() method transforms this into "PLAİN" those two strings get compared and it results to false, because of this client thinks that server does not support "Plain" authentication method. 

Thanks for quick responses!

**Review by Gsantomaggio — APPROVED** [review]

**Comment by Zerpet** [comment]
Thank you for the detailed explanation and the contribution!

**Pull request merged**
