### PR TITLE
Change reconnection logic in ReliableBase

### PR DESCRIPTION
**Pull request by ricsiLT**
In response to #150

### CODE REVIEW

**Comment by lukebakken** [comment]
Thank you for your continued contributions. I just returned to work after some PTO, and @Gsantomaggio is out for a bit. We'll get to this when we can!

**Comment by lukebakken** [comment]
@ricsiLT thanks for your patience, I'm reviewing this today.

**Review by lukebakken — CHANGES_REQUESTED** [review]
There are 4 test failures that do not happen on `main`. I'm investigating.

**Comment by ricsiLT** [comment]
Yeah, test failures puzzled me too since I didn't understand why they wouldn't fail on `main` in the first place - chatted about it with @Gsantomaggio on Slack but he was busy with something else so I didn't get a clear answer about those tests :)

**Comment by lukebakken** [comment]
@Gsantomaggio when you get back, let's discuss the remaining test failure. When running the `ConsumeAfterKillConnectionShouldContinueToWork` test we can see that many connections are killed at the end of the test. I'm wondering if the new reconnection logic creates many new connections?

[rabbitmq-stream-dotnet-client-151-failure-log.txt](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/files/9293545/rabbitmq-stream-dotnet-client-151-failure-log.txt)

I'm going to look into how to enable logging while running tests. Not sure how to do that now.

**Comment by Gsantomaggio** [comment]
@ricsiLT Thanks for the PR!
I didn't check the code, but there must be a bug somewhere. 
a lot of connections are recreated 
Screen Shot 2022-08-12 at 09 08 24


This is why the assert `Assert.Equal(1, connectionsKilled);` fails.

**Comment by Gsantomaggio** [comment]
@ricsiLT Thank you again for your contribution. I close this PR in favour of #163 !

**Pull request closed without merging**
