### PR TITLE
issue-304 - solve problem with memory leak. Added closing connection

### PR DESCRIPTION
**Pull request by MikhailTushev**

### CODE REVIEW

**Comment by MikhailTushev** [comment]
[@](https://github.com/rabbitmq/rabbitmq-stream-dotnet-client/issues/304) resolve issue.
 @Gsantomaggio, @lukebakken, check pls

**Comment by Gsantomaggio** [comment]
Thank you for the PR @MikhailTushev,
We will check it soon

**Review by Gsantomaggio — APPROVED** [review]

**Comment by MikhailTushev** [comment]
@Gsantomaggio, Hello, Can i merge? how i can make patch version for this changes?

**Comment by Gsantomaggio** [comment]
>Hello, Can i merge? 

you can't :) 

> how i can make patch version for this changes?

you can't :) ! we will do that as soon as we merge the other pending PR(s)

Thank you

**Pull request merged**
